# Getting Started with R

In our first 'real' week of the course we provide an introduction to R, structured as follows:

- <a href='#What is R?'>What is R?</a>  
-   <a href='#Why R?'>Why R?</a>
-  <a href='#Downloading and installing R'>Downloading and installing R</a>
-   <a href='#Setting up your environment'>Setting up your environment</a>
-   <a href='#Elementary Commands'>Elementary Commands</a>
- <a href='#Object assignment'>Object assignment</a>
-   <a href='#Functions'>Functions</a>
-  <a href='#Data types'>Data types</a>
- <a href='#Data structures'>Data structures</a>
-  <a href='#Loops'>Loops</a>
-  <a href='#Importing files'>Importing files</a>
-  <a href='#Importing packages'>Importing packages</a>
- <a href='#Graphing and visualisation'>Graphing and visualisation</a>

**This is not an exhaustive introduction to R** so don't be surprised if you find things on the web which aren't covered here. This is simply a guide to get you to a level where you'll be able to do useful things in the next week and eventually start teaching yourself. 




### What is R? <a id='What is R?'></a>

R is a programming language created by **R**obert Gentleman and **R**oss Ihaka (get it? R?) at the Department of Statistics at the University of Auckland in New Zealand in 1995. R  is a statistical language in that it was designed with statistical applications in mind, and as a result it has myriad in-built statistical features which make statistical analysis easy to use and intuitive (next term you will see Python is *even more* intuitive). It is freely available and is also the most popular statistical language in the world.

 ### Why R<a id='Why R'></a>



It's an important question! It would have probably been pretty easy to just offer this course entirely in Python, a reasonable choice considering Python is also free, even more intuitive than R and currently world's 3rd most popular programming language (R is 20th). R's huge advantage for applications like hypothesis testing, plotting statistical distributions, regression, matrix algebra and many other mathematical tasks is that it is **purpose-built** to deal with them. As we will soon see R's in-built functions mean that as soon as you load your environment (well get to what an environment is soon, don't worry), R is ready to go for statistical analysis. In Python by contrast we have to download and install several extra packages for us to be able to do statistics, and once we do the commands (code we need to write) to conduct them are longer as we have to call these packages every time we want to use them.

As for other statistical languages like SAS, SPSS and STATA - **R is free**! Of course being at LSE means we get access to lots of paid software and most workplaces also do too, however the best thing about R being free is that while the paid packages you have access to at any point in your working or academic lives are liable to change R will always be an option! That's not to disincentivise you from learning STATA or any other paid language, it's just that R is a pretty natural choice for the statistical language used in an open-source course about using code to do statistics, maths, economics and metrics.

   ### Downloading and installing R <a id='Downloading and installing R'></a>



R is available for download at The R Project's website: https://www.r-project.org. It must downloaded through 'mirrors' or sites hosted by a range of universities. The mirror you choose doesn't matter, each will download the same version of R. Once you download the relevant version for your operating system you'll be prompted to install it as you'd install any other package to your computer. 

Once you've installed R open the terminal application (pre-installed as Terminal on Mac, Ubuntu on Linux (Dell laptops) and cmd.exe for Windows) and type the letter 'r' to check that R has installed correctly. If it has then you should see a short preamble about the version of R you're using and then the command prompt '>', which is where you can type your first command:

In [1]:
print('Hello World')

[1] "Hello World"


It's a bit of a cheesy first command but it's essentially a computer science rite of passage that that's the first one you ever write. Another good starting command to try is:

In [2]:
1+1

[1] 2

If you want to try a 'cool' one then try: 

In [3]:
for (i in 1:100) print(i)

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10
[1] 11
[1] 12
[1] 13
[1] 14
[1] 15
[1] 16
[1] 17
[1] 18
[1] 19
[1] 20
[1] 21
[1] 22
[1] 23
[1] 24
[1] 25
[1] 26
[1] 27
[1] 28
[1] 29
[1] 30
[1] 31
[1] 32
[1] 33
[1] 34
[1] 35
[1] 36
[1] 37
[1] 38
[1] 39
[1] 40
[1] 41
[1] 42
[1] 43
[1] 44
[1] 45
[1] 46
[1] 47
[1] 48
[1] 49
[1] 50
[1] 51
[1] 52
[1] 53
[1] 54
[1] 55
[1] 56
[1] 57
[1] 58
[1] 59
[1] 60
[1] 61
[1] 62
[1] 63
[1] 64
[1] 65
[1] 66
[1] 67
[1] 68
[1] 69
[1] 70
[1] 71
[1] 72
[1] 73
[1] 74
[1] 75
[1] 76
[1] 77
[1] 78
[1] 79
[1] 80
[1] 81
[1] 82
[1] 83
[1] 84
[1] 85
[1] 86
[1] 87
[1] 88
[1] 89
[1] 90
[1] 91
[1] 92
[1] 93
[1] 94
[1] 95
[1] 96
[1] 97
[1] 98
[1] 99
[1] 100


Which prints the numbers 1,2,3...100 in a fraction of a second! This is called a 'for loop', which we cover in more detail in <a href='#Loops'>Loops</a>

That's all we'll cover in the way of commands for now but in the rest of this notebook we'll give you lots more to try out. The important thing is that you can write commands in your terminal and that these give the expected output. Installation can sometimes be a bit of a hassle, as can the next section  <a href='#Setting up your environment'>Setting up your environment</a>, but once you get through these two stages there is huge potential for what we can do next. If your installation hasn't worked then check out the relevant online guides available for installing R and running it in the terminal.

  ### Setting up your environment<a id='Setting up your environment'></a>



If you're looking at your first few commands and their output (admit it, you tried to make R print the numbers between 1 and 100,000,000,000,000 and it broke) then you may notice that R is kind of annoying and ugly. Or at least, it's not like the R we're seeing here. For example it's probably all black and white, you can't click any part of your code and edit it and those little '>' prompts aren't particularly appealing. Don't worry, that's because we haven't set up our enviornment yet. What we need is the Jupyter Notebook, the development environment we're writing this notebook in. 

We've used the word 'environment' a lot without explaining what it means. Essentially the environment we code in is just program(s) we use to run and edit our code. In the previous section your environment was just the terminal. If you had the idea to write your code in a text file and then run it in terminal then the text editor you used would also be part of your environment. Jupyter notebooks are online web-applications which are a really user-friendly environment. They run from your web browser (Safari, Explorer, Firefox) and as mentioned they are the environment that this entire course was written on! Oh and you're reading one right now. Jupyter is so-called because it began as a way to support the languages Julia, Python and R in the same platform. It's currently able to support many more languages, including Ruby, Java, C and more. 

Before you ask: web-application doesn't mean we will always need an internet connection. Once we've downloaded the Jupyter Notebook software we can run it on our browser even without an internet connection. It might seem strange at first to be on Safari while everyone else in your flat/house/halls is complaining the wifi is broken but that's just one of the many cool things about being able to code. 

To install the Jupyter Notebook software we also need to have Python installed. Python is pre-installed on Mac and Linux (together called Unix btw) but needs to be downloaded and installed for Windows. You can do this at https://www.python.org/downloads/ just like you did for R but once again if you're having trouble then please consult the internet's many troubleshooting guides. Once Python is installed we head to: https://jupyter.org/install to install Jupyter Notebooks. The easiest way to do this is to download 'Anaconda', which is another environment, from: https://www.anaconda.com. All you do then is click the 'Jupyter' app on the Anaconda welcome screen and you will get taken straight to Jupyter open in your default browser! There other ways to install Jupyter but we'll leave those to you if you've got your own preferences.

Once you've opened Jupyter you'll be shown your 'User' folder, which will itself be a collection of folders. Now is a good time to create your own 'Hands-on Econ' folder, which you can do using the 'New' button at the top right corner. Once you're in your new folder click new again and create an R notebook. You should see an essentially blank webpage containing just a line like the one below:

If so then congrats! You're in! This is the environment which we'll use for the rest of this course, both for the rest of this term and for all of next term too. Try the commands out from before to make sure everything is working as it did in the terminal but if it is then well done - you're ready to learn how to code. The last important thing is to name the file your using by clicking the 'Untitled' text at the top of your browser and naming the file: 'MT Week 2'.

### Data types<a id='Data types'></a>

We've already seen `'Hello World'` and `1`, but what are they? These are examples of 2 of R's 4 main data types: character, numerical, logical and integer. To find what the type of an object is we use the `class()` function:


In [4]:
class('Hello World')

[1] "character"

In [5]:
class(1)

[1] "numeric"

Character is the simplest: it is just anything surrounded by quotation marks. So `'Hello World'`,`'Hello Worlds'`, `'1'` and `'qfln1f19p4hr17ofi'` are all characters. Numeric are also pretty simple: they are just any number, positive or negative, whole or not. Logical may sound strange but it just the values `TRUE`,`T`, `FALSE` and `F`:

In [6]:
class(TRUE)

[1] "logical"

It's important to note that `TRUE` and `FALSE` *don't* have quotation marks around them. If they did they'd be characters like anything else:

In [7]:
class('TRUE')

[1] "character"

The last (main) data type is 'integer', which may sound simple (the integers are just the positive and negative whole numbers, so -32, 4 and 0 are all integers) but when we check:

In [8]:
class(-32)


[1] "numeric"

In [9]:
class(4)



[1] "numeric"

In [10]:
class(0)

[1] "numeric"

We get numeric, not integer. The key is that we have to *tell* R that these are integers by adding L to their end, so:

In [11]:
class(-32L)

[1] "integer"

In [12]:
class(4L)

[1] "integer"

In [13]:
class(0L)

[1] "integer"

Are all integers.

These are the four main data types in R, so now we know what they are we can introduce 'commands' or the things we can do with them. 

### Operators <a id='Operators'></a>



We've seen also seen the `print()` and `+` commands, so what are they? `print()` is kind of its own thing, so we'll start with it. `print()` will simply return whatever we type between the brackets. This might sound quite intuitive but be careful because if we want to print only the text within the brackets then we need to include quotation marks `''`  or `""`. If we tried to use the command:




```r
print(Hello World)``` 

then we would get an error because R doesn't know what `Hello World` means. When we put quotation marks around it we make `Hello World` into the character `'Hello World'`. 

`print()` is not an operator. It's a command and it's kind of unique. Everything else we'll cover here *is* an operator. There are two main kinds of operators: numeric and logical. The main numeric operators are all pretty self explanatory: `+`,`-`,`*` (times), `/` (divide) and `^` (to the power of). These all work as you'd expect:

In [14]:
2+2


[1] 4

In [15]:
4-3



[1] 1

In [16]:
3*5



[1] 15

In [17]:
9/3



[1] 3

In [18]:
2^5

[1] 32

As for the logical operators these are also pretty self-explanatory. The main ones are: `>`,`<`,`>=`,`<=`,`==` (equal to),`!=` (not equal to), `x|y` (x or y), `x&y`, `isTRUE(x)` (is x TRUE?). So:

In [19]:
4>3

[1] TRUE

In [20]:
4<3

[1] FALSE

In [21]:
3>=3

[1] TRUE

In [22]:
3<=3

[1] TRUE

In [23]:
TRUE==T

[1] TRUE

In [24]:
4!=4

[1] FALSE

In [25]:
4>3|4<3

[1] TRUE

In [26]:
4>3&4<3

[1] FALSE

In [27]:
isTRUE(4<3)

[1] FALSE

Operators in R aren't hard (they get a little harder in Python) but they do require practice to get familar with. 

### Object assignment<a id='Object assignment'></a>



You might have guessed that we can store variables in R. This is called 'object assignment' and its a little bit strange in R. Most major programs (as we'll see in Python in Lent) let you store variables with the `=` operator. This makes sense! `x=5` is a telling Python that x is equal to 5! R is a little less friendly. The trouble is that R will *sometimes* let us use `=` to assign variables, but sometimes it won't. The solution is that R will always let us assign variables using `<-`, so instead of `x=5` we can write `x<-5` and get exactly what we'd expect.

In [28]:
x<-5
print(x)

[1] 5


Notice how we didn't write `print('x')`? That's because even though `x` is now a variable, `'x'` will always be a character, because it is between two quotation marks. To see this notice:

In [29]:
print('x')

[1] "x"


Once we've assigned a value to a variable we can treat that variable just like we were treating the value we've assigned it to.

In [30]:
class(x)

[1] "numeric"

In [31]:
x+5

[1] 10

In [32]:
x==5

[1] TRUE

Even better, if we've got more than one variable we can treat all of them like their underlying values:

In [33]:
y<-7 
print(x+y)

[1] 12


In [34]:
x==y

[1] FALSE

One word of advice is ***don't*** assign variables to functions (like `print`, or others we'll see below). It's a really easy way to make sure code that works perfectly will screw up for no reason. 

Other languages make it much easier to characters (like 'a') than R but R still lets us assign characters to variables:

In [35]:
x<-'y'
print(x)

[1] "y"


In [36]:
x=='y'

[1] TRUE

The trouble is if we try to do anything more we get hit with errors, like we would if we tried to run: `x+'y'`, `x^2` or any other fun commands (which we'll see work fine in Python). The reason for this is that R is primarily a statistical language. We can do essentially all of the things we can do to characters in other languages in R but we have to use clunkier commands which we'll introduce as needed. 

 ### Data structures <a id='Data structures'></a>



Data structures are useful ways of storing data in R. We can't import an Excel table into R, store it and use *per se*, but we can import it as a 'dataframe' (we'll explain this in a moment) and then use that dataframe for our analysis. There are four main types of data structure in R and we'll see examples of each.

Vectors are our first type, and are written in the form `c(x,y,z,...)`. They are really easy ways to store 'collections' of things, and to operate over everything in that collection. For example:

In [37]:
a<-c(1,2,3)
print(a)

[1] 1 2 3


In [38]:
print(a*2)

[1] 2 4 6


In [39]:
b<-c(4,7,9)
print(a*b)

[1]  4 14 27


We *can* store different data types in the same list but if we do then R will usually default all of the objects to characters and we'll lose our abaility to operate over them:

In [40]:
x<-c(1,2,'a')

In [41]:
class(x)
class(a)

[1] "character"

[1] "numeric"

So R is telling us the vector is a 'character vector' or all its entries are characters. If we had just logicals (TRUE/FALSE) and numerics (1,2,3.3) then R would default the logicals to numerics where TRUE is 1 and FALSE is 0:

In [42]:
y<-c(1,2,TRUE)

In [43]:
class(y)

[1] "numeric"

In [44]:
print(y*2)

[1] 2 4 2


We can also index vectors by using square brackets, so:

In [45]:
b[1]

[1] 4

In [46]:
b[c(1,3)]

[1] 4 9

Which is giving us the first and then the first and third elements of b. There are two more data types we need to worry about: matricies and dataframes. Matricies are literally just the matricies you spent all of linear algebra worrying about. They are created using the `matrix()` command and then specifying a vector of values and the number of rows/columns:

In [59]:
M<-matrix(c(1,2,3,
            4,5,6,
            7,8,9), ncol=3, byrow=TRUE)
M

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

The `byrow` attribute just refer to the order in which our values progress. Matricies can be operated over using `+` and `-` as expected

In [60]:
M<-matrix(c(1,2,3,
            4,5,6,
            7,8,9), ncol=3, byrow=TRUE)
N<-matrix(c(1,1,1,
            1,1,1,
            1,1,1), ncol=3, byrow=TRUE)
M+N
M-N

[,1] [,2] [,3]
[1,] 2    3     4  
[2,] 5    6     7  
[3,] 8    9    10

[,1] [,2] [,3]
[1,] 0    1    2   
[2,] 3    4    5   
[3,] 6    7    8

But when we use `*` and `/` we get unusual results:

In [49]:
M<-matrix(c(1,2,3,
            4,5,6,
            7,8,9), ncol=3, byrow=TRUE)
N<-matrix(c(1,1,1,
            1,1,1,
            1,1,1), ncol=3, byrow=TRUE)
M*N
M/N

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

The usual operators operate over each individual element of the matrix, so they don't reflect *matrix multiplication* or *matrix division*. These are conducted with: `%*%` and `%/%`

In [50]:
M%*%N
M%/%N

[,1] [,2] [,3]
[1,]  6    6    6  
[2,] 15   15   15  
[3,] 24   24   24

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6   
[3,] 7    8    9

If you've forgotten your matrix algebra then don't worry we'll go back over it in Week 5: Linear Algebra. The last and most important data structure is the dataframe. Dataframes are essentially the closest thing that R (and Python) have to spreadsheets and they are the bread and butter of data science. We *can* create dataframes but most of our analysis if probably going to be done with ones we've imported from the internet or from our laptops. Either way, we can create them as: 

In [51]:
D<-data.frame(c(1,2,3),c(4,5,6),c(7,8,9))
colnames(D)<-c('A','B','C')
rownames(D)<-c('a','b','c')
print(D)

  A B C
a 1 4 7
b 2 5 8
c 3 6 9


If it seems simple then that's because it is, but don't underestimate the power of being able to essentially use an Excel spreadsheet within a program as powerful as R (or later Python). Remember the table we imported last week and created the regression and heatmap with? That was a dataframe. One of the big advantages is that R doesn't need to show us the whole dataframe so it can easily handle them with hundreds of thousands or millions of entries. If we tried to use excel for those purposes it would probably crash eventually. As expected we can manipulate dataframes and index over them:

In [52]:
print(D*2)

  A  B  C
a 2  8 14
b 4 10 16
c 6 12 18


In [53]:
print(D['A'])

  A
a 1
b 2
c 3


In [54]:
print(D[1])

  A
a 1
b 2
c 3


As can be seen we can index over dataframes by their column names *AND* their column place numbers. We can do the same for rows, but place a comma after the first entry to indicate the entry is a row, not a column:

In [55]:
print(D['a',])

  A B C
a 1 4 7


In [56]:
print(D[1,])

  A B C
a 1 4 7


We can also edit their entries which is extremely useful. 

In [57]:
D[1,2]<-5

In [58]:
print(D)

  A B C
a 1 5 7
b 2 5 8
c 3 6 9


Dataframes are really really **really** useful so make sure you get some familiarity with them.

 ### Functions<a id='Functions'></a>



R's functions are what really set it apart for statistical analysis and general mathematical applications (like metrics). Without having to do anything special we can instantly find $\sin(23)$, find the mean and standard deviation of ${43.432,56.234,875.54,342.876,4.9689}$, round $\pi$ to 37 digits and generate 29 random observations from the normal distribution $N(23,3214)$. Not convinced?

In [69]:
sin(23)

[1] -0.8462204

In [70]:
mean(c(43.432,56.234,875.54,342.876,4.9689))
sd(c(43.432,56.234,875.54,342.876,4.9689))

[1] 264.6102

[1] 367.1222

In [71]:
round(pi,37)

[1] 3.141593

In [72]:
rnorm(29,23,3214)

[1]  3371.6368  5954.8618   395.1229 -1450.2064   585.1986  -268.1553
 [7]  1639.6552  2905.1501 -3367.3817  -128.3525 -1785.3671  2657.8643
[13]  1557.8056  1823.7633  4885.6347 -1599.1238   252.0441  -531.8167
[19]   768.0324  1880.3155 -3694.0156  1373.2794  6229.7726  5690.1223
[25] -5615.7687  2970.4510 -2456.4929 -4347.7074 -2087.7184

This might not seem like much but just take note of how little code this took. The command for $sin(x)$ is literally just `sin(x)`! We can't do this in Python or in many other free languages and that's why R is so useful. It'd be a fool's errand to try and list all the useful commands here but please check out: https://www.statmethods.net/management/functions.html for a good overview of what's possible.

 ### Loops <a id='Loops'></a>



We already saw loops in action when we printed the values between 1 and 100. This was an example of the `for` loop, which is the only one we will cover in R (as usual, the story's a little different for Python). The `for` loop works on the principle of '*for* everything in this collection of things, I'll do whatever you write next'. So in our original `for` loop:

```R
for (i in 1:100) print(i)
```

The `for` loop simply took each element in 1,2,...,100 and printed it. Why? Well `1:100` is simply the range of all numbers between 1 and 100 inclusive.


In [74]:
1:100

[1]   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
 [19]  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
 [37]  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
 [55]  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
 [73]  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
 [91]  91  92  93  94  95  96  97  98  99 100

We can write `for` loops over any collection of objects with the same structure, for, the brackets, then the collection of objects, then closed brackets, then the command. So another example is: 

In [76]:
a<-c('H','a','n','d','s',' ','O','n',' ','E','c','o','n')
for (i in a) print(i)

[1] "H"
[1] "a"
[1] "n"
[1] "d"
[1] "s"
[1] " "
[1] "O"
[1] "n"
[1] " "
[1] "E"
[1] "c"
[1] "o"
[1] "n"


`for` loops can be used for a huge amount of applications and we won't go through them here but you'll see plenty throughout the course in R and Python.

  ### Importing files<a id='Importing files'></a>



Importing files is an extremely important part of learning to code in R. It's the step when we upgrade from having a cool toy to a powerful tool. The main type of file we're likely to be importing is the '**c**omma **s**eperated **v**ariable'  file, which uses the extension .csv, and is also just known as a csv. csv's are essentially best thought of as just text files (like a Word document for example) where each row constitutes the row of a table and each comma constitutes a different column. So for example:

```
a,b
c,d
```

is the csv version of:

In [79]:
matrix(c('a','b','c','d'),ncol=2,byrow=T)

[,1] [,2]
[1,] a    b   
[2,] c    d

Every Excel file can be easily saved as a csv when you choose 'Save As' and most databases are likely to have the file you need in a .csv format. We'll get to what to do if they don't later in the course but right now if you can import, open and use any csv file from the web or your computer then you'll be doing pretty well. So let's import our first csv from the web:

In [97]:
data <- read.csv('https://data.bls.gov/cew/data/api/2017/3/area/29000.csv')

In [98]:
data

area_fips own_code industry_code agglvl_code size_code year qtr
1    29000     0        10            50          0         2017 3  
2    29000     1        10            51          0         2017 3  
3    29000     1        101           52          0         2017 3  
4    29000     1        1013          53          0         2017 3  
5    29000     1        102           52          0         2017 3  
6    29000     1        1021          53          0         2017 3  
7    29000     1        1022          53          0         2017 3  
8    29000     1        1023          53          0         2017 3  
9    29000     1        1024          53          0         2017 3  
10   29000     1        1025          53          0         2017 3  
11   29000     1        1026          53          0         2017 3  
12   29000     1        1027          53          0         2017 3  
13   29000     1        1028          53          0         2017 3  
14   29000     1        31-33         54          0         2017 3  
15   29000     1        323           55          0         2017 3  
16   29000     1        3231          56          0         2017 3  
17   29000     1        32311         57          0         2017 3  
18   29000     1        323111        58          0         2017 3  
19   29000     1        339           55          0         2017 3  
20   29000     1        3399          56          0         2017 3  
21   29000     1        33991         57          0         2017 3  
22   29000     1        339910        58          0         2017 3  
23   29000     1        44-45         54          0         2017 3  
24   29000     1        441           55          0         2017 3  
25   29000     1        4413          56          0         2017 3  
26   29000     1        44131         57          0         2017 3  
27   29000     1        441310        58          0         2017 3  
28   29000     1        445           55          0         2017 3  
29   29000     1        4451          56          0         2017 3  
30   29000     1        44511         57          0         2017 3  
⋮    ⋮         ⋮        ⋮             ⋮           ⋮         ⋮    ⋮  
2866 29000     5        813219        58          0         2017 3  
2867 29000     5        8133          56          0         2017 3  
2868 29000     5        81331         57          0         2017 3  
2869 29000     5        813311        58          0         2017 3  
2870 29000     5        813312        58          0         2017 3  
2871 29000     5        813319        58          0         2017 3  
2872 29000     5        8134          56          0         2017 3  
2873 29000     5        81341         57          0         2017 3  
2874 29000     5        813410        58          0         2017 3  
2875 29000     5        8139          56          0         2017 3  
2876 29000     5        81391         57          0         2017 3  
2877 29000     5        813910        58          0         2017 3  
2878 29000     5        81392         57          0         2017 3  
2879 29000     5        813920        58          0         2017 3  
2880 29000     5        81393         57          0         2017 3  
2881 29000     5        813930        58          0         2017 3  
2882 29000     5        81394         57          0         2017 3  
2883 29000     5        813940        58          0         2017 3  
2884 29000     5        81399         57          0         2017 3  
2885 29000     5        813990        58          0         2017 3  
2886 29000     5        814           55          0         2017 3  
2887 29000     5        8141          56          0         2017 3  
2888 29000     5        81411         57          0         2017 3  
2889 29000     5        814110        58          0         2017 3  
2890 29000     5        99            54          0         2017 3  
2891 29000     5        999           55          0         2017 3  
289

  ### Importing packages <a id='Importing packages'></a>

  ### Graphing and visualisation<a id='Graphing and visualisation'></a>